apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

ext {
    extName = 'BacaKomik'
    pkgNameSuffix = 'id.bacakomik'
    extClass = '.BacaKomik'
    extVersionCode = 11
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' } // ← ini penting
    }
}

apply from: "$rootDir/common.gradle"
